---

- name: Looking up users
  ansible.builtin.getent:
    database: passwd

- name: "Add authorized keys for user pi"
  ansible.posix.authorized_key:
    user: "pi"
    state: present
    key: '{{ item }}'
  loop: "{{ ssh_keys_to_add }}"
  when: "'pi' in ansible_facts.getent_passwd"
  become: true
  become_user: root

- name: "Remove authorized keys for user pi"
  ansible.posix.authorized_key:
    user: "pi"
    state: absent
    key: '{{ item }}'
  loop: "{{ ssh_keys_to_remove }}"
  when: "'pi' in ansible_facts.getent_passwd"
  become: true
  become_user: root

- name: "Add authorized keys for user xbian"
  ansible.posix.authorized_key:
    user: "xbian"
    state: present
    key: '{{ item }}'
  loop: "{{ ssh_keys_to_add }}"
  when: "'xbian' in ansible_facts.getent_passwd"
  become: true
  become_user: root

- name: "Remove authorized keys for user xbian"
  ansible.posix.authorized_key:
    user: "xbian"
    state: absent
    key: '{{ item }}'
  loop: "{{ ssh_keys_to_remove }}"
  when: "'xbian' in ansible_facts.getent_passwd"
  become: true
  become_user: root
