name: ansible-lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: ansible-lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup python for ansible
        uses: actions/setup-python@v5

      - name: Install ansible and ansible-lint
        run: pip install ansible ansible-lint

      - name: Show ansible-lint version
        run: ansible-lint --version

      - name: Run ansible-lint
        run: ansible-lint --show-relpath .
